"""empty message

Revision ID: 4e4b27d949e4
Revises: 
Create Date: 2020-05-02 17:06:24.294503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4b27d949e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.Column('Username', sa.String(length=20), nullable=False),
    sa.Column('Password', sa.String(length=60), nullable=False),
    sa.Column('isbn_book_reviewed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
